/**
 * GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * This file is auto-generated by the generateMatcher.js script.
 * Run 'npm run generate-matcher' to update it.
 */

export const middlewareMatcherConfig = {
  matcher: [
    // Match all paths except those starting with excluded paths or file paths with extensions
    '/((?!api|_next|_vercel|.*\\.[^/]+$).*)',
    // Include root path
    '/'
  ]
};
