/**
 * @fileoverview EWA v2 Type Definitions
 * @module lib/ewa/types
 * @see BLOCK9.5_ETHICAL_AUTONOMY.md
 *
 * Core types for Ethical Autonomy & Self-Learning Governance
 */

/**
 * Severity levels for ethical insights
 */
export type SeverityLevel = 'low' | 'moderate' | 'critical';

/**
 * Insight confidence score (0-1)
 */
export type ConfidenceScore = number;

/**
 * Ethical insight generated by EWA v2
 */
export interface EthicalInsight {
  timestamp: string;
  insight_id: string;
  severity: SeverityLevel;
  severity_score: number; // 0-1 raw score
  description: string;
  recommended_action: string;
  confidence: ConfidenceScore;
  evidence: Record<string, unknown>;
  source: 'statistical' | 'ml' | 'hybrid';
  requires_human_review: boolean;
}

/**
 * Trust Trajectory Indicator data
 */
export interface TrustTrajectory {
  timestamp: string;
  tti_score: number; // 0-100
  components: {
    eii: number;
    consent_stability: number;
    security_posture: number;
  };
  trend: 'improving' | 'stable' | 'declining';
  velocity: number; // Rate of change
  volatility: number; // Stability measure
}

/**
 * Statistical analysis result
 */
export interface StatisticalAnalysis {
  eii_analysis: {
    current: number;
    delta_30d: number;
    delta_90d: number;
    volatility: number;
    trend: 'up' | 'down' | 'stable';
  };
  consent_analysis: {
    total_users: number;
    withdrawal_rate: number;
    category_shifts: Record<string, number>;
    volatility: number;
  };
  security_analysis: {
    current_score: number;
    anomalies_detected: number;
    trend: 'improving' | 'stable' | 'declining';
  };
}

/**
 * ML analysis result (optional layer)
 */
export interface MLAnalysis {
  anomalies: Array<{
    metric: string;
    score: number;
    explanation: string;
  }>;
  forecast: {
    eii_30d: number;
    confidence: number;
  };
  patterns: Array<{
    pattern_id: string;
    description: string;
    significance: number;
  }>;
}

/**
 * Combined analysis result
 */
export interface AnalysisResult {
  timestamp: string;
  statistical: StatisticalAnalysis;
  ml?: MLAnalysis;
  insights: EthicalInsight[];
  trust_trajectory: TrustTrajectory;
}

/**
 * Review queue entry for critical insights
 */
export interface ReviewQueueEntry {
  entry_id: string;
  timestamp: string;
  insight: EthicalInsight;
  status: 'pending' | 'approved' | 'rejected';
  reviewed_by?: string;
  reviewed_at?: string;
  notes?: string;
}

/**
 * Autonomous analysis ledger entry
 */
export interface AutonomousAnalysisEntry {
  entry_id: string;
  ledger_entry_type: 'autonomous_analysis';
  block_id: '9.5';
  title: string;
  status: 'verified' | 'pending_review';
  approved_date: string;
  responsible_roles: string[];
  insights: Array<{
    insight_id: string;
    severity: SeverityLevel;
  }>;
  summary: string;
  next_review: string;
  hash: string;
  merkleRoot: string;
  signature: string | null;
}

